using Microsoft.EntityFrameworkCore;
using ToDo.DAL.Models;

namespace ToDo.DAL.Repositories;

/// <summary>
/// EF Core-based repository for TaskItem.
/// </summary>
public class TaskItemRepository : ITaskItemRepository
{
    private readonly AppDbContext _dbContext;

    public TaskItemRepository(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    /// <summary>
    /// Returns all task items ordered by CreatedAt.
    /// </summary>
    public async Task<IEnumerable<TaskItem>> GetAllAsync()
    {
        return await _dbContext.TaskItems
            .AsNoTracking()
            .OrderBy(t => t.CreatedAt)
            .ToListAsync();
    }

    /// <summary>
    /// Returns a task item by its Id, or null if it doesn't exist.
    /// </summary>
    public async Task<TaskItem?> GetByIdAsync(int id)
    {
        return await _dbContext.TaskItems.FindAsync(id);
    }

    /// <summary>
    /// Adds a new task item. Id is generated by the database.
    /// </summary>
    public async Task<TaskItem> AddAsync(TaskItem taskItem)
    {
        // If CreatedAt wasn't set, set it here as a safety net
        if (taskItem.CreatedAt == default)
        {
            taskItem.CreatedAt = DateTime.UtcNow;
        }

        _dbContext.TaskItems.Add(taskItem);
        await _dbContext.SaveChangesAsync();

        return taskItem;
    }

    /// <summary>
    /// Updates an existing task item, or returns null if it doesn't exist.
    /// </summary>
    public async Task<TaskItem?> UpdateAsync(TaskItem taskItem)
    {
        var existing = await _dbContext.TaskItems.FindAsync(taskItem.Id);
        if (existing is null)
        {
            return null;
        }

        // Copy values into the tracked entity
        _dbContext.Entry(existing).CurrentValues.SetValues(taskItem);

        await _dbContext.SaveChangesAsync();
        return existing;
    }

    /// <summary>
    /// Deletes a task by its Id.
    /// </summary>
    public async Task<bool> DeleteAsync(int id)
    {
        var existing = await _dbContext.TaskItems.FindAsync(id);
        if (existing is null)
        {
            return false;
        }

        _dbContext.TaskItems.Remove(existing);
        await _dbContext.SaveChangesAsync();

        return true;
    }
}
